### ISSUE TITLE
[Bug] Error when committing within a submodule with `.git` file

### ISSUE THREAD

**Issue by geordiemhall** [ForkIssues/TrackerWin#1200]
I saw that issue #1115 already exists, but was closed by the submitter without any further info.

After double clicking a submodule to open a new tab in Fork for it, trying to commit something throws an error like:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Repos\MyOuterRepo\Plugins\MySubmodule\.git\COMMITMESSAGE'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Fork.Git.Commands.CommitGitCommand.Execute(GitModule gitModule, String message, Boolean amend, JobProgress progress, Boolean noVerify)
```

I can understand why it can't make that file since the submodule has a `.git` _file_, not a folder. But opening the command prompt in the submodule's directory (via Fork's "Console" button) and committing with `git commit -m "My commit message"` succeeds, so it feels like something Fork could probably support (and I swear it used to? though maybe that was on submodules with an actual `.git` folder).

Could also be user error on my part (needed to add the submodule differently?), but figure even if so it'd be good to have a search result with some answers :)

Fork version: 1.63.0.0

**Comment by DanPristupov** [comment]
I guess, Fork somehow remembers that his repository is not a submodule.

Try to open repository manager and check if this submodule repo is listed here. If it is, remove it and restart the application.

**Comment by ChefkeGremmen** [comment]
I have a similar issue, .git is a file, not a folder, but it gives me the following error;

```
$ git commit --file="C:/Git/project/.git/modules/external/submodule/COMMITMESSAGE"

Can't open perl script ".git/hooks/prepare-commit-msg.pl": Not a directory
```

I also looked in the repository manager, but the submodule repo is nog listed there.

**Comment by DanPristupov** [comment]
@ChefkeGremmen not sure if it's the same issue. Check your `prepare-commit-msg` hook.

**Comment by ChefkeGremmen** [comment]
Thanks for the tip, the issues was that the '.git' folder was hard encoded, after changing it to `$GIT_DIR` it worked like a chime.

**Comment by geordiemhall** [comment]
@DanPristupov Thanks for the suggestion, I opened the repository manager but couldn't see the submodule listed (though did see an empty "folder tree" that could mean it used to have been considered a full repo before I converted to a proper submodule?)

Restarting Fork or something else seems to have done the trick though, and can now commit in the submodule through the GUI 👍
