### ISSUE TITLE
OverflowException with non standard Color Profile

### ISSUE THREAD

**Issue by Mats391** [ForkIssues/TrackerWin#1302]
Found this randomly because I had to debug same issue in our code. The program crashes when you use non sRgb color profile in Windows.

Steps to reproduce:

- Set color profile to scRGB ![image](https://user-images.githubusercontent.com/868580/132376669-3e5843ae-c1b5-4d2b-a1ed-2cc5efd13bd3.png)

- Launch Fork
- Crash

Since I just debugged it for our code, here is our solution:
Remove the ICC Profile from all images used (e.g. using https://exiftool.org/)
```exiftool -ICC_Profile= Foo.Png```
Source: https://www.hanselman.com/blog/dealing-with-images-with-bad-metadata-corrupted-color-profiles-in-wpf
 

Stacktrace
```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=The type initializer for 'Fork.UI.UserControls.FileListUserControl' threw an exception.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Fork.UI.UserControls.RepositoryUserControl.InitializeComponent()
   at Fork.UI.UserControls.RepositoryUserControl..ctor()
   at Fork.UI.TabItemView.ActivateRepositoryViewMode(GitModule gitModule)
   at Fork.TabManager.RestoreSession()
   at Fork.UI.MainWindow.ForkWindow_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Inner Exception 1:
OverflowException: The image data generated an overflow during processing.

Inner Exception 2:
ArithmeticException: Overflow or underflow in the arithmetic operation.

```

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/847#issuecomment-682370957

**Comment by DanPristupov** [comment]
> Since I just debugged it for our code, here is our solution:
> Remove the ICC Profile from all images used (e.g. using https://exiftool.org/)
> ```exiftool -ICC_Profile= Foo.Png```
> Source: https://www.hanselman.com/blog/dealing-with-images-with-bad-metadata-corrupted-color-profiles-in-wpf

That is awesome! Thank you very much for sharing. We will do that!
