### ISSUE TITLE
Stash fails for long path on windows

### ISSUE THREAD

**Issue by ChristophLindemann** [ForkIssues/TrackerWin#1412]
# Description

When trying to `stash`, the command fails with the following error. This happens if one or more of the files have long filenames (> 260).

```
System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fork.Git.Interaction.GitRequest.Execute(JobProgress progress, Boolean silent, EnvironmentVariable[] environmentVariables)
```
![image](https://user-images.githubusercontent.com/16814858/146172212-4e44d61a-8ced-4b30-a015-71625b88f1c5.png)

## System Info

Fork 1.69.4.0
Git: %USERPROFILE%\AppData\Local\Fork\gitInstance\2.33.1\bin\git.exe
`git config --global core.longpaths true`
Windows 10 Enterprise 20H2 (19042.844)

## Log

```
?? 2021-12-06 09:12:17.430 
  ¦¦¦¦¦¦ ¦¦¦¦¦¦   ¦¦¯¦¦¦   ¦¦ _¦¯
¦¦¦   ¦ ¦¦¦¦  ¦¦¦¦¦¦ ¦ ¦¦¦ ¦¦_¦¦    Fork 1.69.4.0
¦¦¦¦¦ ¦ ¦¦¦¦  ¦¦¦¦¦¦ ¦_¦ ¦¦¦¦¦_¦    Git: %USERPROFILE%\AppData\Local\Fork\gitInstance\2.33.1\bin\git.exe
¦¦¦¦  ¦ ¦¦¦   ¦¦¦¦¦¦¯¯¦_  ¦¦¦ ¦_    Update Channel: Develop
¦¦¦¦    ¦ ¦¦¦¦¦¦¦¦¦¦¦ ¦¦¦¦¦¦¦¦ ¦_
 ¦ ¦    ¦ ¦¦¦¦¦¦ ¦ ¦¦ ¦¦¦¦¦ ¦¦ ¦¦      https://fork.dev
 ¦        ¦ ¦ ¦¦   ¦¦ ¦ ¦¦¦ ¦¦ ¦¦
 ¦ ¦    ¦ ¦ ¦ ¦    ¦¦   ¦ ¦ ¦¦ ¦
            ¦ ¦     ¦     ¦  ¦

?? 2021-12-06 09:12:17.457 Start IPC server Fork_Pipe137536_AskPass
?? 2021-12-06 09:12:17.457 Fork_Pipe137536_AskPass: waiting for next event '135'
?? 2021-12-06 09:12:17.457 Start IPC server Fork_Pipe137536_Default
?? 2021-12-06 09:12:17.457 Fork_Pipe137536_Default: waiting for next event '135'
?? 2021-12-06 09:12:17.934 Log target: AppData log file
?? 2021-12-06 09:12:18.077 Last update check: 19-11-2021 13:01:50. Next one: 20-11-2021 13:01:50
?? 2021-12-06 09:12:18.400 Restore workspance 'Work' with 3 tabs
?? 2021-12-06 09:12:18.739      659 ms: Initialize Paddle
...
?? 2021-12-15 11:40:30.851 WindowActivated
?? 2021-12-15 11:40:30.851 Application Window Activated
?? 2021-12-15 11:40:30.851 RefreshRepositoryStatus
?? 2021-12-15 11:40:31.137 Refresh 'TheRepo' status. Updated 971 files
?? 2021-12-15 11:40:31.137 RefreshRepositoryData
?? 2021-12-15 11:40:31.137 TheRepo RefreshRepositoryDataGitCommand DefaultRefresh
?? 2021-12-15 11:40:31.238 TheRepo Repository data are equal. No Changes
?? 2021-12-15 11:40:34.489 WindowActivated
?? 2021-12-15 11:40:34.489 Application Window Activated
?? 2021-12-15 11:40:34.489 RefreshRepositoryStatus
?? 2021-12-15 11:40:34.723 Refresh 'TheRepo' status. Updated 971 files
?? 2021-12-15 11:40:34.723 RefreshRepositoryData
?? 2021-12-15 11:40:34.723 TheRepo RefreshRepositoryDataGitCommand DefaultRefresh
?? 2021-12-15 11:40:34.840 TheRepo Repository data are equal. No Changes
?? 2021-12-15 11:40:35.129 Looking for an associated editor for 'E:\Source\TheRepo\TestHelpers'
?? 2021-12-15 11:40:35.129 Can't find editor for 'E:\Source\TheRepo\TestHelpers'
?? 2021-12-15 11:40:36.017 Application is active. Delaying automatic fetch by 1 minute to not disturb the user.
? 2021-12-15 11:40:50.096 %USERPROFILE%\AppData\Local\Fork\gitInstance\2.33.1\bin\git.exe
? 2021-12-15 11:40:50.096 System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fork.Git.Interaction.GitRequest.Execute(JobProgress progress, Boolean silent, EnvironmentVariable[] environmentVariables)
?? 2021-12-15 11:40:50.106 WindowActivated
?? 2021-12-15 11:40:50.106 Application Window Activated: skip (CreatePartialStashWindow)
?? 2021-12-15 11:40:50.135 RefreshRepositoryStatus
?? 2021-12-15 11:40:50.425 Refresh 'TheRepo' status. Updated 971 files
?? 2021-12-15 11:40:50.425 RefreshRepositoryData
?? 2021-12-15 11:40:50.425 TheRepo RefreshRepositoryDataGitCommand Stashes, Revisions, Status
?? 2021-12-15 11:40:50.587 TheRepo Repository data are equal. No Changes
```

# Expected behaviour
Either it should work (at least with `git config --global core.longpaths true`) or it should give some more meaningfull error, preferably with path to which files are the problem

**Comment by floky** [comment]
Hey there! Long time ago issue but just leaving this here as food for thought.
Have you tried to enable long files support in Windows? There are 2 different ways to do it as described here for example:
https://thegeekpage.com/make-windows-11-accept-file-paths-over-260-characters/

The same steps are available for Windows 10.
