### ISSUE TITLE
[BUG] Fork crashes when attempting to interactively rebase with "The filename or extension is too long"

### ISSUE THREAD

**Issue by SmithPlatts** [ForkIssues/TrackerWin#1579]
Attempting to interactively rebase, hitting a merge commit which contains a file with a filename length that exceeds Window's allowed; Fork crashes with:

```
? 2022-07-05 13:51:36.391 System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fork.Git.Interaction.GitRequest.Execute(Boolean silent)
```

I have the appropriate setting configured which allows Git for Windows to handle long path names.

Fork version: 1.74.1
Windows: Windows 10 21H2 (19044)
Git: 2.36.1 (Fork instance)

**Comment by DanPristupov** [comment]
You should probably enable long file paths on Windows:

https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10

**Comment by SmithPlatts** [comment]
I assume, based on this comment, that Fork specifies the `longPathAware` declaration in the manifest? If so, awesome.

However, I am not an admin on my work machine, and cannot make this change. It also doesn't really resolve the fact that Fork hard crashes from this.

**Comment by DanPristupov** [comment]
No, I didn't know about that manifest. I will investigate.

**Comment by snapstreamjoe** [comment]
I have this registry setting changed and I also experienced this.

Also, once I received this error, I was not even able to abort the rebase, I had to go to the command line to roll it back by hand.

**Comment by BeachyHeadCode** [comment]
I am encountering this on version 1.86.1.0. See log file [fork.log](https://github.com/fork-dev/TrackerWin/files/12131128/fork.log). I set the registry to long file path and still encountering the crash, with a system restart to ensure it taking effect.

git version: 2.40.1.windows.1

**Comment by SmithPlatts** [comment]
Any update on this one @DanPristupov ?
