### ISSUE TITLE
[BUG] 1.75 Silent Crashing on Opening (+ on open repo / preferences)

### ISSUE THREAD

**Issue by HalenWKB** [ForkIssues/TrackerWin#1596]
Firstly, I love Fork! Great Sourcetree replacement!

Though sadly, for the past week my Fork app has been regularly failing to open (Silent crashes on opening). Restarting my machine will sometimes fix it but now even that seems to have stopped working. If I re-install Fork I can open the app but then I get the same silent crash if I try to open any repo (or even the preferences window) restarting post re-install tends to reliably (but temporarily) fix this though.

So my current morning routine is: Try and open Fork (won't open, silent crash) > re-install Fork > Open repo/prefs and have app crash > Restart machine > Fork works fine.

I'm on a Win10 machine and have triple checked my color management settings (In ref to this): 
https://github.com/fork-dev/TrackerWin/issues/847#issuecomment-682370957

Attached are my logs after each crash type but they don't seem to provide anything useful.

[CrashOnOpen_fork.log](https://github.com/fork-dev/TrackerWin/files/9185191/CrashOnOpen_fork.log)
[CrashOnOpenRepo_fork.log](https://github.com/fork-dev/TrackerWin/files/9185192/CrashOnOpenRepo_fork.log)
[CrashOnOpenPreferences_fork.log](https://github.com/fork-dev/TrackerWin/files/9185193/CrashOnOpenPreferences_fork.log)

**Comment by DanPristupov** [comment]
> I'm on a Win10 machine and have triple checked my color management settings (In ref to this):

That should not be the case anymore. We removed the color profile info from all images.

Do you have enough free space on the hard disk?

Can you find the crash report in the Windows Event Viewer? There must be a pair of records for each application crash and the second one contains the call stack.

**Comment by HalenWKB** [comment]
Thanks for getting back so fast :) 

I have 10gb of free space (Surely enough?)

Call stack from the error:

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at System.Reflection.MetadataImport._Enum(IntPtr, Int32, Int32, System.Reflection.MetadataEnumResult ByRef)
   at System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].PopulateProperties(Filter, System.RuntimeType, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Reflection.RuntimePropertyInfo>>, Boolean[], ListBuilder`1<System.Reflection.RuntimePropertyInfo> ByRef)
   at System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].PopulateProperties(Filter)
   at System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetListByName(Char*, Int32, Byte*, Int32, MemberListType, CacheType)
   at System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Populate(System.String, MemberListType, CacheType)
   at System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetMemberList(MemberListType, System.String, CacheType)
   at System.RuntimeType.GetPropertyCandidates(System.String, System.Reflection.BindingFlags, System.Type[], Boolean)
   at System.RuntimeType.GetMember(System.String, System.Reflection.MemberTypes, System.Reflection.BindingFlags)
   at System.Xaml.Schema.TypeReflector.GetNonIndexerProperty(System.String)
   at System.Xaml.Schema.TypeReflector.LookupProperty(System.String)
   at System.Xaml.XamlType.LookupMember(System.String, Boolean)
   at System.Windows.Baml2006.WpfXamlMember.get_BaseUnderlyingMember()
   at System.Windows.Baml2006.WpfXamlMember.LookupUnderlyingMember()
   at System.Xaml.XamlMember.get_UnderlyingMember()
   at System.Xaml.XamlMember.get_AreAttributesAvailable()
   at System.Xaml.XamlMember.LookupTypeConverter()
   at System.Xaml.XamlMember.get_TypeConverter()
   at System.Xaml.XamlObjectWriter.Logic_CreatePropertyValueFromValue(MS.Internal.Xaml.Context.ObjectWriterContext)
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadDeferredContent(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.ResourceDictionary.CreateObject(System.Windows.Baml2006.KeyRecord)
   at System.Windows.ResourceDictionary.OnGettingValue(System.Object, System.Object ByRef, Boolean ByRef)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(System.Object, System.Object ByRef, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValue(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValue(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValue(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValue(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.FetchResource(System.Object, Boolean, Boolean, Boolean, Boolean ByRef)
   at System.Windows.FrameworkElement.FindResourceInternal(System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, System.Windows.DependencyProperty, System.Object, System.Object, Boolean, Boolean, System.Windows.DependencyObject, Boolean, System.Object ByRef)
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.StaticResourceExtension.TryProvideValueImpl(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.StaticResourceExtension.ProvideValueInternal(System.IServiceProvider, Boolean)
   at System.Windows.StaticResourceExtension.ProvideValue(System.IServiceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)
   at System.Xaml.XamlObjectWriter.Logic_ProvideValue(MS.Internal.Xaml.Context.ObjectWriterContext)
   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(MS.Internal.Xaml.Context.ObjectWriterContext)
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Fork.UI.UserControls.NotificationBarUserControl.InitializeComponent()
   at Fork.UI.UserControls.NotificationBarUserControl..ctor()
```

```
Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Activator.CreateInstance(System.Type, System.Object[])
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(System.Type, System.Object[])
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstance(System.Type, System.Object[])
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(System.Object[])
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(System.Xaml.XamlType, System.Object[])
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(System.Xaml.XamlType, System.Object[])
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateInstance(System.Xaml.XamlType, System.Object[])
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(MS.Internal.Xaml.Context.ObjectWriterContext)
   at System.Xaml.XamlObjectWriter.WriteStartMember(System.Xaml.XamlMember)
   at System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Fork.UI.UserControls.RepositoryUserControl.InitializeComponent()
   at Fork.UI.UserControls.RepositoryUserControl..ctor()
   at Fork.UI.Controls.ClosableTabItem.ActivateRepositoryViewMode(Fork.Git.GitModule)
   at Fork.TabManager.RestoreSession()
   at Fork.UI.MainWindow.ForkWindow_Loaded(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

**Comment by HalenWKB** [comment]
And the non-call stack error event mentions the following:

```
Faulting application name: Fork.exe, version: 1.75.0.0, time stamp: 0x62c84bfd
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1826, time stamp: 0x617d5271
Exception code: 0xe0434352
Fault offset: 0x0012ca42
Faulting process ID: 0x5a94
Faulting application start time: 0x01d8a0c7387a9b92
Faulting application path: C:\Users\User of the Epicus\AppData\Local\Fork\app-1.75.0\Fork.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 96b39aef-78b6-4b8f-a7a9-aa099cc50800
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by zbyna** [comment]
I have similar problems, but only the 1st start after os starting fails. Restarting fork seems fixes it. I am on win7 sp2, I will post log when I reach my computer.

**Comment by HalenWKB** [comment]
> I have similar problems, but only the 1st start after os starting fails. Restarting fork seems fixes it. I am on win7 sp2, I will post log when I reach my computer.

Thanks, that would be handy :) 
Though for me I can't restart Fork since it won't open in the first place (And when it does open but crashes on open repo- restarting Fork hasn't helped)

**Comment by zbyna** [comment]
```
Podpis problému:
  Název události problému (Name of problem event):	CLR20r3
  Podpis problému (Problem description) 01:	Fork.exe
  Podpis problému 02:	1.74.1.0
  Podpis problému 03:	6289f999
  Podpis problému 04:	mscorlib
  Podpis problému 05:	4.8.4110.0
  Podpis problému 06:	5de6d97a
  Podpis problému 07:	4657
  Podpis problému 08:	7
  Podpis problému 09:	N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
  Operation system:	6.1.7601.2.1.0.256.48
  ID of national environment:	1029
  Další informace (Additional info) 1:	0a9e
  Další informace 2:	0a9e372d3b4ad19135b953a78882e789
  Další informace 3:	0a9e
  Další informace 4:	0a9e372d3b4ad19135b953a78882e789
```
```
Název protokolu:Application
Zdroj:         Application Error
Datum:         27.7.2022 1:45:56
ID události:   1000
Kategorie úlohy:(100)
Úroveň:        Chyba
Klíčová slova: Klasické nastavení
Uživatel:      Není k dispozici
Počítač:       decak-PC
Popis:
Název chybující aplikace: Fork.exe, verze: 1.74.1.0, časové razítko: 0x6289f999
Název chybujícího modulu: KERNELBASE.dll, verze: 6.1.7601.23002, časové razítko: 0x5507b1dc
Kód výjimky: 0xe0434352
Posun chyby: 0x0000c44d
ID chybujícího procesu: 0xfc4
Čas spuštění chybující aplikace: 0x01d8a149d6701f7c
Cesta k chybující aplikaci: C:\Users\decak\AppData\Local\Fork\app-1.74.1\Fork.exe
Cesta k chybujícímu modulu: C:\Windows\syswow64\KERNELBASE.dll
ID zprávy: 17988053-0d3d-11ed-bbbe-005056c00008
Kód XML události:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-26T23:45:56.000000000Z" />
    <EventRecordID>38911</EventRecordID>
    <Channel>Application</Channel>
    <Computer>decak-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Fork.exe</Data>
    <Data>1.74.1.0</Data>
    <Data>6289f999</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.23002</Data>
    <Data>5507b1dc</Data>
    <Data>e0434352</Data>
    <Data>0000c44d</Data>
    <Data>fc4</Data>
    <Data>01d8a149d6701f7c</Data>
    <Data>C:\Users\decak\AppData\Local\Fork\app-1.74.1\Fork.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>17988053-0d3d-11ed-bbbe-005056c00008</Data>
  </EventData>
</Event>
```

```
Název protokolu:Application
Zdroj:         .NET Runtime
Datum:         27.7.2022 1:45:55
ID události:   1026
Kategorie úlohy:Není
Úroveň:        Chyba
Klíčová slova: Klasické nastavení
Uživatel:      Není k dispozici
Počítač:       decak-PC
Popis:
Aplikace: Fork.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.PlatformNotSupportedException

Informace o výjimce: System.TypeLoadException
   na Fork.Accounts.NotificationManager.SendWindowsNotification(System.String)
   na Fork.Accounts.NotificationManager.SendToastNotification(Int32)
   na Fork.Accounts.NotificationManager+<>c__DisplayClass30_1.<Refresh>b__3()
   na System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   na System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   na System.Windows.Threading.DispatcherOperation.InvokeImpl()
   na System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   na MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   na MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   na System.Windows.Threading.DispatcherOperation.Invoke()
   na System.Windows.Threading.Dispatcher.ProcessQueue()
   na System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   na MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   na MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   na System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   na System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   na System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   na MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   na MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   na System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   na System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   na System.Windows.Application.RunDispatcher(System.Object)
   na System.Windows.Application.RunInternal(System.Windows.Window)
   na System.Windows.Application.Run(System.Windows.Window)
   na Fork.App.Main()

Informace o výjimce: System.Reflection.TargetInvocationException
   na System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   na System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   na System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   na <Module>.Main(System.String[])


Kód XML události:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-26T23:45:55.000000000Z" />
    <EventRecordID>38910</EventRecordID>
    <Channel>Application</Channel>
    <Computer>decak-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Aplikace: Fork.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.PlatformNotSupportedException

Informace o výjimce: System.TypeLoadException
   na Fork.Accounts.NotificationManager.SendWindowsNotification(System.String)
   na Fork.Accounts.NotificationManager.SendToastNotification(Int32)
   na Fork.Accounts.NotificationManager+&lt;&gt;c__DisplayClass30_1.&lt;Refresh&gt;b__3()
   na System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   na System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   na System.Windows.Threading.DispatcherOperation.InvokeImpl()
   na System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   na MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   na MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   na System.Windows.Threading.DispatcherOperation.Invoke()
   na System.Windows.Threading.Dispatcher.ProcessQueue()
   na System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   na MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   na MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   na System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   na System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   na System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   na MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   na MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   na System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   na System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   na System.Windows.Application.RunDispatcher(System.Object)
   na System.Windows.Application.RunInternal(System.Windows.Window)
   na System.Windows.Application.Run(System.Windows.Window)
   na Fork.App.Main()

Informace o výjimce: System.Reflection.TargetInvocationException
   na System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   na System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   na System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   na &lt;Module&gt;.Main(System.String[])

</Data>
  </EventData>
</Event>
```

**Comment by DanPristupov** [comment]
@zbyna try to reinstall Fork using https://fork.dev/update/win/ForkInstaller.exe

**Comment by zbyna** [comment]
@DanPristupov  It works! No problem even if after windows restarting. Thanks!

**Comment by HalenWKB** [comment]
Unfortunately still crashing for me on re-install. Still have to: re-install > open repo crashes > restart > works fine until PC restarts again

**Comment by zbyna** [comment]
>  C:\Users\User of the Epicus\AppData\Local\Fork\app-1.75.0\Fork.exe

@HalenWKB  I noticed you have spaces in username  ```\User of the Epicus\```. It is sometimes the cause of “strange” app behaviour. What about install Fork to another path, or I have to admit, try more complicated way,  [strip out spaces from username](https://codeburst.io/changing-a-profile-name-in-windows-9da6c02234e4).

**Comment by HalenWKB** [comment]
Oooft... Can't find a way to install to a different directory so I'll try stripping out username spaces this weekend... ty for the tip!

**Comment by DanPristupov** [comment]
The whitespace should not be a problem.

@HalenWKB How many other apps do you run? When you have a problem again, try to close them all and repeat.

**Comment by HalenWKB** [comment]
Still fails with no other apps open.
Beginning to suspect it may be related to this: [Applications Fail to Start with Kernelbase.dll](https://answers.microsoft.com/en-us/windows/forum/all/applications-fail-to-start-with-kernelbasedll/44a4c2ad-a43f-479b-b026-bcdc2ff01285)
Fork is the only app that fails to open for me but its a Kernelbase error so will let you know if the steps here help...

**Comment by HalenWKB** [comment]
Alright, 1 week of no crashing- perhaps a windows update fixed my corrupted Kernelbase.dll? ¯\_(ツ)_/¯ I'm just gonna blame cosmic rays and mark this as closed...
Thanks for the for the help though :)
