### ISSUE TITLE
Crash on startup with AccessViolationException

### ISSUE THREAD

**Issue by kermmeer** [ForkIssues/TrackerWin#1702]
I've got this error since my computer crashed from a bad memory exception. This error is persistent for me and even reinstalling the application, version **1.79.0.0**, doesn't help (I'm making sure the fork folder in `%localappdata%` is gone as well). 

The stacktrace I get is the following:
```Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Security.Policy.PEFileEvidenceFactory.GetPublisherCertificate(Microsoft.Win32.SafeHandles.SafePEFileHandle, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.Security.Policy.PEFileEvidenceFactory.GeneratePublisherEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(System.Type)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(System.Type)
   at System.Security.Policy.Evidence.GenerateHostEvidence(System.Type, Boolean)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(System.Type)
   at System.Security.Policy.Evidence.GetHostEvidence(System.Type, Boolean)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(System.Type)
   at System.Security.Policy.Evidence.GenerateHostEvidence(System.Type, Boolean)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(System.Type)
   at System.Security.Policy.Evidence+RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence+EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(System.AppDomain, System.String, System.String ByRef)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(System.AppDomain, System.String)
   at System.Configuration.ClientConfigPaths..ctor(System.String, Boolean)
   at System.Configuration.ClientConfigPaths.GetPaths(System.String, Boolean)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(System.Configuration.Internal.IInternalConfigRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at NLog.Config.LoggingConfigurationWatchableFileLoader.TryLoadFromAppConfig()
   at NLog.Config.LoggingConfigurationWatchableFileLoader.Load(NLog.LogFactory, System.String)
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLoggerThreadSafe(System.String, System.Type)
   at NLog.LogManager.GetCurrentClassLogger()
   at Fork.App..cctor()

Exception Info: System.TypeInitializationException
   at Fork.App.Main()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.Main(System.String[])```

**Comment by DanPristupov** [comment]
```
  at System.Security.Policy.PEFileEvidenceFactory.GetPublisherCertificate(Microsoft.Win32.SafeHandles.SafePEFileHandle, System.Runtime.CompilerServices.ObjectHandleOnStack)
...
  at NLog.LogFactory.get_Configuration()
```

That's doesn't look good. I suppose your .Net installation is corrupted.

**Comment by kermmeer** [comment]
Ok just got this "fixed". I did a reinstall once more of Fork and a windows tool to check all my .net framework installations which froze my whole pc. And like always a forced reboot fixed everything 🤦 . Thanks for the help and sorry for the waste of time 🙇
