### ISSUE TITLE
[Bug] Crash on Windows 11 22H2 when left idle with a repo open

### ISSUE THREAD

**Issue by mikerochip** [ForkIssues/TrackerWin#1710]
Fork version 1.79.2.0

Me and a teammate are getting sporadic crashes. We are both on Alienware X15 R2s running Windows 11 22H2.

Fork will just crash after being left open and idle after some time. No warning, error, dialog, or anything. We have a private repository open, but again not being interacted with.

Looking at windows event viewer, I see this error:

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at Fork.IO.Ipc.PipeStreamExtensions.ReadString(System.IO.Pipes.PipeStream)
   at Fork.App.AskPassIpcMessageHandler(System.IO.Pipes.NamedPipeServerStream)
   at Fork.IpcServer.EventLoop(System.Threading.CancellationTokenSource, System.IO.Pipes.NamedPipeServerStream)
   at Fork.IpcServer.<.ctor>b__8_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by DanPristupov** [comment]
> Me and a teammate are getting sporadic crashes.

Can you contact me by email, please (support@fork.dev)?
