### ISSUE TITLE
Crash when pasting Chinese character in commit

### ISSUE THREAD

**Issue by jakehuang2232** [ForkIssues/TrackerWin#1734]
```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(System.Runtime.InteropServices.ComTypes.FORMATETC ByRef, System.Runtime.InteropServices.ComTypes.STGMEDIUM ByRef)
   at System.Windows.DataObject+OleConverter.GetDataInner(System.Runtime.InteropServices.ComTypes.FORMATETC ByRef, System.Runtime.InteropServices.ComTypes.STGMEDIUM ByRef)
   at System.Windows.DataObject+OleConverter.GetDataFromOleHGLOBAL(System.String, System.Runtime.InteropServices.ComTypes.DVASPECT, Int32)
   at System.Windows.DataObject+OleConverter.GetDataFromBoundOleDataObject(System.String, System.Runtime.InteropServices.ComTypes.DVASPECT, Int32)
   at System.Windows.DataObject+OleConverter.GetData(System.String, Boolean, System.Runtime.InteropServices.ComTypes.DVASPECT, Int32)
   at System.Windows.DataObject+OleConverter.GetData(System.String, Boolean)
   at System.Windows.DataObject.GetData(System.String, Boolean)
   at System.Windows.DataObject.GetData(System.String)
   at System.Windows.DataObject.GetData(System.Type)
   at Fork.UI.UserControls.CommitUserControl.OnCommitSubjectPaste(System.Object, System.Windows.DataObjectPastingEventArgs)
   at System.Windows.DataObjectPastingEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Documents.TextEditorCopyPaste._DoPaste(System.Windows.Documents.TextEditor, System.Windows.IDataObject, Boolean)
   at System.Windows.Documents.TextEditorCopyPaste.Paste(System.Windows.Documents.TextEditor)
   at System.Windows.Documents.TextEditorCopyPaste.OnPaste(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.Input.CommandBinding.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(System.Object, System.Windows.Input.ExecutedRoutedEventArgs, System.Windows.Input.CommandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.UIElement.OnExecutedThunk(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(System.Object, System.Windows.IInputElement, Boolean)
   at System.Windows.Input.RoutedCommand.ExecuteCore(System.Object, System.Windows.IInputElement, Boolean)
   at System.Windows.Input.CommandManager.TranslateInput(System.Windows.IInputElement, System.Windows.Input.InputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(System.Object, System.Windows.Input.KeyEventArgs)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawKeyboardActions, Int32, Boolean, Boolean, Int32)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(System.Windows.Interop.MSG ByRef, System.Windows.Input.ModifierKeys)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at System.Windows.Threading.Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority, System.Delegate, System.Object)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   at System.Windows.Interop.HwndSource+WeakEventPreprocessMessage.OnPreprocessMessage(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Fork.App.Main()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.Main(System.String[])
```

**Comment by DanPristupov** [comment]
What should I do to reproduce the problem?
What Windows version do you use?

**Comment by jakehuang2232** [comment]
Paste "僅變更其中一個" in the "Commit subject"

**Comment by DanPristupov** [comment]
Works for me:

https://user-images.githubusercontent.com/618115/208853984-e2f03772-c28d-40b0-b467-8539e7c7c876.mov

What Windows version do you use?

**Comment by jakehuang2232** [comment]
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.22621.0 Microsoft Windows NT 10.0.22621.0


 LCID             Name             DisplayName
----             ----             -----------
1028             zh-TW            Chinese (Traditional, Taiwan)


https://user-images.githubusercontent.com/83938127/208860193-416f5161-7639-4af3-8448-881c7611435b.mp4

Crash without any warning

**Comment by jakehuang2232** [comment]
Update:
If I paste the string copied from Description field or text editor like vscode
then it won't crash

https://user-images.githubusercontent.com/83938127/208869367-39638719-7d67-440d-b41d-a3afe8c0b32e.mp4

But if i copy from firefox then it will crash

**Comment by jakehuang2232** [comment]
Update:
Copy string "主要目標"
Clipboard data (firefox)
![圖片](https://user-images.githubusercontent.com/83938127/208865654-114c2a93-3839-4040-9233-612272ed1fcb.png)

Clipboard data (vscode)
![圖片](https://user-images.githubusercontent.com/83938127/208865754-90eb863a-e3da-4d53-8c33-787410251126.png)

**Comment by DanPristupov** [comment]
I tried to install Firefox, but it still doesn't crash.

<img width="664" alt="Screenshot 2023-03-29 at 18 02 39" src="https://user-images.githubusercontent.com/618115/228598838-34c8e8cb-7179-404e-a4d9-91aa18269509.png">

**Comment by ck97756** [comment]
The problem seems to be solved
I haven't run into it in fork version 1.82.1.0
Thanks for the help

**Comment by DanPristupov** [comment]
:(
