### ISSUE TITLE
If you attempt to discard changes on an empty file

### ISSUE THREAD

**Issue by hyperlogic** [ForkIssues/TrackerWin#1891]
You get the following error:
```
[Internal]: System.IO.IOException: Incorrect function.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
   at Fork.Git.Commands.DiscardFileChangesGitCommand.DeleteFile(GitModule gitModule, ChangedFile file, Boolean isReadOnly)
```

**Comment by DanPristupov** [comment]
No, I can't reproduce that.
https://github.com/fork-dev/TrackerWin/assets/618115/1640d1da-2725-4c9a-b5db-40185d6c7862
