### ISSUE TITLE
[BUG] Fork crashes when draging branch in left navigation pane

### ISSUE THREAD

**Issue by CommanderAlchemy** [ForkIssues/TrackerWin#2040]
Fork Version: 1.89.2.0
Windows 11: Up to date

When trying to drag a branch in the left pane crashes fork immediately. 
This worked fine previously so not sure if this was fork update or windows update?

1. Checkout branch
2. Select branch 
3. Start to drag with the mouse mouse
![image](https://github.com/fork-dev/TrackerWin/assets/3089330/73bd0f65-56c4-4ffa-a464-b82ed2a9915b)

```
Faulting application name: Fork.exe, version: 1.89.2.0, time stamp: 0x6503253d
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2215, time stamp: 0x83983b0b
Exception code: 0xe0434352
Fault offset: 0x000000000006531c
Faulting process id: 0x0x2D2C
Faulting application start time: 0x0x1D9F5275008284E
Faulting application path: C:\Users\user\AppData\Local\Fork\app-1.89.2\Fork.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f8bf087d-0fe5-439c-b2b3-a8fa2957c765
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(System.Runtime.InteropServices.ComTypes.IDataObject, IOleDropSource, Int32, Int32[])
   at System.Windows.OleServicesContext.OleDoDragDrop(System.Runtime.InteropServices.ComTypes.IDataObject, IOleDropSource, Int32, Int32[])
   at System.Windows.DragDrop.OleDoDragDrop(System.Windows.DependencyObject, System.Windows.DataObject, System.Windows.DragDropEffects)
   at System.Windows.DragDrop.DoDragDrop(System.Windows.DependencyObject, System.Object, System.Windows.DragDropEffects)
   at Fork.UI.Controls.TreeViewControlItem.OnMouseMove(System.Windows.Input.MouseEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Fork.App.Main()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.Main(System.String[])
   ```

**Comment by CommanderAlchemy** [comment]
I think this was related to some dotnet / dotnet sdk itself. 
Since installing new version it somehow fixed itself.
