### ISSUE TITLE
Error on trying stash 813 files

### ISSUE THREAD

**Issue by foal** [ForkIssues/TrackerWin#2109]
Fork 1.92.0.0
```
System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Fork.Git.Interaction.GitRequest.Execute(JobMonitor monitor, Boolean silent, EnvironmentVariable[] environmentVariables)
```

Stash of the same set but in two portions (384+429) is working.

**Comment by xenoblitz** [comment]
@DanPristupov I have the same issue. 
Potentially the reason is this:
https://github.com/dotnet/runtime/issues/58492

It seems that with enough files to stash even the new larger Windows limit is reached. I guess a potential solution would be to split the stashing into multiple commands in sequence. Shame this results in multiple stashes but at least it could help alleviate some of the problem.

**Comment by sukanmanas** [comment]
I do get the same error popup. I think the problem was cause by the window system  string exceed a certain number 
8191 characters or something. because Stash command on GIT fork will try to Stash each file separately so the command will include  the path of each file that you want to stash. This is ok for 100-300 file but for 600 or more the command will be too long for window operation to process that's why it throw this error. **To sum it up you could just use console command in the top right and use ` git stash push -m "$your stash name" --staged ` to stash all staged file instead**

**Comment by DanPristupov** [comment]
@sukanmanas use the stash button on the toolbar
