### ISSUE TITLE
Sync results in `FileNotFoundException` regarding stashes

### ISSUE THREAD

**Issue by rhys-vdw** [ForkIssues/TrackerWin#2353]
Version: 2.1.0.0

Sync button fails with this issue:
```
[Internal]: System.IO.FileNotFoundException: Could not find file 'C:\Users\Vivian\enter-the-chronosphere.git\logs\refs\stash'.
File name: 'C:\Users\Vivian\enter-the-chronosphere.git\logs\refs\stash'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Fork.Git.Commands.LeanBranching.LeanBranching.Step0Stash(GitModule gitModule, JobMonitor monitor)
```

There are no changes (staged or unstaged).

**Comment by DanPristupov** [comment]
Is this a new repository? We'll try to reproduce this.

**Comment by rhys-vdw** [comment]
Newly cloned from GitHub, with a fresh install of fork.

We actually had this issue with a different team member about a year ago but she just stopped using sync and it has since gone away. This one was with a new team member today.

**Comment by DanPristupov** [comment]
Try to create a stash with some change. Then sync should become fixed.

**Comment by rhys-vdw** [comment]
Yes, that fixes it, thanks.

Interestingly the issue came back for one team member after she deleted her only stash, so it's not just a fresh clone issue.
