### ISSUE TITLE
App crash after update to 2.2.0 with message virus or potentially unwanted software

### ISSUE THREAD

**Issue by Ramo-Y** [ForkIssues/TrackerWin#2357]
Hi Dan,

After the update, Fork is no longer starting, Elastic Security has displayed a virus message because of Fork and I see the following in the Fork logs:

```
◽️ 2024-10-31 12:11:03.374 Squirrel: ApplyReleasesImpl: Writing files to app directory: C:\Users\%USERNAME%\AppData\Local\Fork\app-2.2.0
◽️ 2024-10-31 12:11:03.444 Squirrel: LogHost: Rigging execution stub for Fork_ExecutionStub.exe to C:\Users\%USERNAME%\AppData\Local\Fork\Fork.exe
◽️ 2024-10-31 12:11:03.914 Squirrel: ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\%USERNAME%\AppData\Local\Fork\app-2.2.0\Fork.exe]
◽️ 2024-10-31 12:11:04.466 Squirrel: ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\%USERNAME%\AppData\Local\Fork\app-2.2.0\Fork.exe: System.ComponentModel.Win32Exception (0x80004005): Operation did not complete successfully because the file contains a virus or potentially unwanted software
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
◽️ 2024-10-31 12:11:04.466 Squirrel: ApplyReleasesImpl: Starting fixPinnedExecutables
◽️ 2024-10-31 12:11:04.469 Squirrel: ApplyReleasesImpl: Examining Pin: File Explorer.lnk
◽️ 2024-10-31 12:11:04.469 Squirrel: ApplyReleasesImpl: Examining Pin: Fork.lnk
◽️ 2024-10-31 12:11:04.484 Squirrel: ApplyReleasesImpl: Examining Pin: PowerShell 7 (x64).lnk
◽️ 2024-10-31 12:11:04.501 Squirrel: ApplyReleasesImpl: Examining Pin: Visual Studio 2022 (2).lnk
◽️ 2024-10-31 12:11:04.501 Squirrel: ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
◽️ 2024-10-31 12:11:04.519 Squirrel: ApplyReleasesImpl: Processing shortcut 'C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Fork.lnk'
◽️ 2024-10-31 12:11:04.519 Squirrel: ApplyReleasesImpl: Old shortcut target: 'C:\Users\%USERNAME%\AppData\Local\Fork\Fork.exe'
◽️ 2024-10-31 12:11:04.519 Squirrel: ApplyReleasesImpl: New shortcut target: 'C:\Users\%USERNAME%\AppData\Local\Fork\Fork.exe'
◽️ 2024-10-31 12:11:04.519 Squirrel: ApplyReleasesImpl: Old iconPath is: 'C:\Users\%USERNAME%\AppData\Local\Fork\Fork.exe'
◽️ 2024-10-31 12:11:04.534 Squirrel: ApplyReleasesImpl: Finished shortcut successfully
◽️ 2024-10-31 12:11:04.534 Squirrel: ApplyReleasesImpl: Fixing up tray icons
◽️ 2024-10-31 12:11:04.534 Squirrel: ApplyReleasesImpl: cleanDeadVersions: checking for version 2.2.0
◽️ 2024-10-31 12:11:04.534 Squirrel: ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-2.1.0
◽️ 2024-10-31 12:11:04.534 Squirrel: ApplyReleasesImpl: cleanDeadVersions: exclude new version folder app-2.2.0
◽️ 2024-10-31 12:11:06.176 Squirrel: Utility: Starting to delete folder: C:\Users\%USERNAME%\AppData\Local\Fork\app-1.99.3
◽️ 2024-10-31 12:11:06.176 Squirrel: Utility: Starting to delete folder: C:\Users\%USERNAME%\AppData\Local\Fork\app-2.0.0
◽️ 2024-10-31 12:11:06.187 Squirrel: Utility: Now deleting folder: C:\Users\%USERNAME%\AppData\Local\Fork\app-1.99.3
◽️ 2024-10-31 12:11:06.187 Squirrel: Utility: Now deleting folder: C:\Users\%USERNAME%\AppData\Local\Fork\app-2.0.0
🔷 2024-10-31 12:11:06.498 Version: 2.2.0
🔷 2024-10-31 12:11:06.498 Value: <![CDATA[
<p>Rework uncommitted changes options in Checkout and Create Branch dialogs
Add syntax highlighting for erlang, elixir and dart
Improved: Wrap text in error dialog</p>

]]>
```

And this is from the `Squirrel-ProcessStart.log`:
```
[31.10.24 12:11:16] info: Program: Starting Squirrel Updater: --processStartAndWait Fork.exe
[31.10.24 12:11:16] info: Program: Want to launch 'C:\Users\%USERNAME%\AppData\Local\Fork\app-2.2.0\Fork.exe'
[31.10.24 12:11:16] error: Program: File C:\Users\%USERNAME%\AppData\Local\Fork\app-2.2.0\Fork.exe doesn't exist in current release
[31.10.24 12:11:16] fatal: Finished with unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

I have also restarted my computer but it still won't start and no message appears in the logs. However, I can still work with version 2.1.0.

**Comment by DanPristupov** [comment]
> error: Program: File C:\Users\%USERNAME%\AppData\Local\Fork\app-2.2.0\Fork.exe doesn't exist in current release

Looks like `Fork.exe` has beed deleted. Try to reinstall the application and then run update again.

**Comment by Ramo-Y** [comment]
Just did it, now 2.1.0 is installed again and it works. Thanks for the quick response!

**Comment by DanPristupov** [comment]
I almost got a heart attack 😀

**Comment by Ramo-Y** [comment]
Me too 😆
