### ISSUE TITLE
App crashes when selecting commit text which includes a bug tracker reference

### ISSUE THREAD

**Issue by RoystonS** [ForkIssues/TrackerWin#342]
Version: Git-Fork Windows 1.35.0.0

I often want to copy an issue number from one commit to another, but now I've turned on bug tracking references in my Git Fork for Windows, any attempt even to select text from a commit, where the selection crosses a bug tracking reference link, causes Git Fork to crash completely.

Here's a little video of Git Fork crashing after I've selected some commit text that attempts to include a bug tracking link. Fork hangs at the 0:08 mark, then crashes.

![GitForkCrash](https://user-images.githubusercontent.com/19773/60091388-603db700-973c-11e9-8eb8-74fd1cd92374.gif)

**Comment by DanPristupov** [comment]
I can't reproduce that. Can you try to reboot the computer please?

**Comment by Otiel** [comment]
I've reproduced this, with GitHub issue tracker. Nothing specific is logged into `C:\Users\[user]\AppData\Local\Fork\logs\fork.log`

Restarting the PC doesn't change anything.

**Comment by jerone** [comment]
Also confirmed! Also nothing specific found in the logs.

**Comment by felixhirt** [comment]
i cannot reproduce this bug (Jira server issue tracker), but i noticed that i cannot select the first character in the commit message if it starts with an issue tracker link. Just throwing this in here because it seems really minor. Just tell me if i should open a separate issue for that

**Comment by DanPristupov** [comment]
@felixhirt can you select it backward (starting from end till the start)?

**Comment by jerone** [comment]
I can still confirm this issue. On 2 different machines. Latest Fork version. Any commit with issue-tracker links. Both in subject & description. Selecting only text is fine, but as soon as you select text + link, it crashes.

Two rules:
1. `(?!^|\b|\s|\n|\()#(\d+)(?:$|\b|\s|\n|\))` + `https://org.visualstudio.com/proj/_workitems/edit/$1`
2. `(?!^|\B|\s|\n|\()PR\s?(\d+)(?:$|\b|\s|\n|\))` + `https://org.visualstudio.com/_git/proj/pullrequest/$1`

**Comment by DanPristupov** [comment]
@jerone both work fine on my computer 😕. Not sure what can make the difference...

Lack of crash report is also strange

**Comment by jerone** [comment]
> Lack of crash report is also strange

`C:\Users\<user>\AppData\Local\Fork\logs\fork.log`, right? Nothing in there before I restart Fork.

I do find it strange that the log is cleared when Fork is restarted.

Also, sometimes I takes me a while to reproduce. Other times I happens instantly.

**Comment by RoystonS** [comment]
@DanPristupov I've rebooted (sorry it took 8 days!) and the problem still exists.

**Comment by RoystonS** [comment]
I've managed to get an error trace out of Windows Event Viewer:

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Unrecoverable system error.
Stack:
   at System.Environment.FailFast(System.String)
   at MS.Internal.Invariant.FailFast(System.String, System.String)
   at System.Windows.Documents.TextPointerBase.MoveToNextInsertionPosition(System.Windows.Documents.ITextPointer, System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointer.MoveToNextInsertionPosition(System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointer.System.Windows.Documents.ITextPointer.MoveToNextInsertionPosition(System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointer.System.Windows.Documents.ITextPointer.GetNextInsertionPosition(System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextEditorMouse.OnMouseMoveWithFocus(System.Windows.Documents.TextEditor, System.Windows.Input.MouseEventArgs)
   at System.Windows.Documents.TextEditorMouse.OnMouseMove(System.Object, System.Windows.Input.MouseEventArgs)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Fork.App.Main()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.Main(System.String[])
```

**Comment by DanPristupov** [comment]
@RoystonS great!

This seems to be tricky. Fork in not in the call stack.

But at least we have the source: https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Documents/TextPointerBase.cs,87505e7a51e3caca

**Comment by RoystonS** [comment]
Yeah, my heart always sinks when somebody gives me a crashing call stack and my app is nowhere to be seen. :(

I'm guessing one of those Asserts has failed?  Give me a shout if you want me to run a tweaked Fork or something to get more diagnostics.

**Comment by DanPristupov** [comment]
> I'm guessing one of those Asserts has failed?

Most likely, yes.

The text control consists of multiple text elements: plain text, hyperlink text, paragraph, etc.

> internal static bool **MoveToNextInsertionPosition**(...)

Since the crash is caused by the looking for next insert point it can be related to hyperlink bounds. 

There must be some common pattern:
- May be only messages which end with a hyperlink crash.
- May be messages without space between plain text and hyperlink crash

@jerone in your case, is the crash reproducible on some *particular* messages?

**Comment by jerone** [comment]
> @jerone in your case, is the crash reproducible on some _particular_ messages?

Yeah, maybe... I could (for now) only reproduce it when the message ended with an hyperlink:
```
Implement XXX. Closes #12345678
```

I select `XXX` and as soon as I move my cursor to the end of `#12345678`, it crashes.
Stopping halfway `#12345678` does not crash it.

It looks like the last character is the issue!

**Comment by Otiel** [comment]
I can reproduce it 100% with a simple `Fixes #12345678` text in the commit description.

>as soon as I move my cursor to the end of #12345678, it crashes.
>Stopping halfway #12345678 does not crash it.

Same here.

**Comment by felixhirt** [comment]
> 
> 
> @felixhirt can you select it backward (starting from end till the start)?

yes, thats what i did. it just stops selecting at the second char
![select_commit_message](https://user-images.githubusercontent.com/34443877/60671902-73efc880-9e74-11e9-9999-b7fd435dea54.gif)
Also, i too can reproduce the crash if the issuetracker link is at the end of the commit

**Comment by DanPristupov** [comment]
I fixed both cases. The fix will be available in Fork 1.36.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/618115/60720857-55e59f00-9f2c-11e9-8d82-f29f9b270fce.gif)

Thank you to everyone!

**Comment by RoystonS** [comment]
Wonderful - thank you!  Purely out of curiosity, do you know what caused it to fail for some people but not others?

**Comment by DanPristupov** [comment]
@RoystonS Jerone mentioned the reason some comments above (https://github.com/ForkIssues/TrackerWin/issues/342#issuecomment-508429146)

Most probably the crash (and incorrect selection too) was caused by a bug in the selection range calculation in WPF.

**Comment by DanPristupov** [comment]
I just released Fork 1.36

**Comment by RoystonS** [comment]
Thank you - updated and it all works perfectly. Thank you.

**Comment by jerone** [comment]
Also confirmed working 👍
