### ISSUE TITLE
Problem installing on Windows: Cannot find git instance

### ISSUE THREAD

**Issue by siburny** [ForkIssues/TrackerWin#42]
I just downloaded the latest version from your website. Went to install it: entered my name and email, and path to my projects folder. Then I got a popup with the error message:

```
Cannot find git instance at: 'C:\Users\maxr\AppData\Local\Fork\git\bin\git.exe'
```

Checked `C:\Users\maxr\AppData\Local\Fork\`, and it doesn't contain a `git` subfolder. It does contain a log file.

Based on my interpretation of the log file, Fork tried to download portable Git in 7z archive and extract it, but received the warning and failed to continue (although it did extracted content of 7z archive).

I manually copied Git folder where it needs to go, and everything is working fine now

On a related note: why not use the already installed version of Git that's available on PATH.

Full log file:
```
D 2018-11-16 16:04:33.550 Loading settings.
I 2018-11-16 16:04:33.587 Start ipc server Fork_27328_Pipe_AskPass
D 2018-11-16 16:04:33.589 Waiting for next cross-process event '160'
I 2018-11-16 16:05:04.064 7Zip found at 'C:\ProgramData\maxr\Fork\app-1.23.1\7z.exe'.
I 2018-11-16 16:05:04.064 Git distrib found at 'C:\ProgramData\maxr\Fork\app-1.23.1\PortableGit-2.18.0-64-bit.7z'.
I 2018-11-16 16:05:04.064 Running 'C:\ProgramData\maxr\Fork\app-1.23.1\7z.exe' with arguments '-o../git x "C:\ProgramData\maxr\Fork\app-1.23.1\PortableGit-2.18.0-64-bit.7z" -y'.
D 2018-11-16 16:05:15.634 Output: 
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Scanning the drive for archives:
1 file, 38640192 bytes (37 MiB)

Extracting archive: C:\ProgramData\maxr\Fork\app-1.23.1\PortableGit-2.18.0-64-bit.7z
WARNING:
C:\ProgramData\maxr\Fork\app-1.23.1\PortableGit-2.18.0-64-bit.7z
Can not open the file as [7z] archive
The file is open as [PE] archive

--
Path = C:\ProgramData\maxr\Fork\app-1.23.1\PortableGit-2.18.0-64-bit.7z
Open WARNING: Can not open the file as [7z] archive
Type = PE
Physical Size = 38640192
CPU = x86
Characteristics = Executable 32-bit
Created = 2017-04-05 17:33:08
Headers Size = 1024
Checksum = 38647281
Name = 7zS.sfx.exe
Image Size = 503808
Section Alignment = 4096
File Alignment = 512
Code Size = 382976
Initialized Data Size = 106496
Uninitialized Data Size = 0
Linker Version = 14.10
OS Version = 6.0
Image Version = 0.0
Subsystem Version = 6.0
Subsystem = Windows GUI
DLL Characteristics = Relocated NX-Compatible TerminalServerAware
Stack Reserve = 1048576
Stack Commit = 4096
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment = FileVersion: 16.4.0.0
FileVersion: 16.04
ProductVersion: 16.4.0.0
ProductVersion: 16.04
CompanyName: Igor Pavlov
FileDescription: 7z Setup SFX
InternalName: 7zS.sfx
LegalCopyright: Copyright (c) 1999-2016 Igor Pavlov
OriginalFilename: 7zS.sfx.exe
ProductName: 7-Zip
----
Path = [0]
Size = 38155688
Packed Size = 38155688
Virtual Size = 38155688
Offset = 477184
--
Path = [0]
Type = 7z
Offset = 515
Physical Size = 38155167
Tail Size = 6
Headers Size = 60355
Method = LZMA:28 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Archives with Warnings: 1
Folders: 11
Files: 5721
Size:       255432988
Compressed: 38640192

E 2018-11-16 16:05:15.659 Git instance installation failed and can not be found at 'C:\Users\maxr\AppData\Local\Fork\git\bin\git.exe'.
I 2018-11-16 16:05:15.659 Git instance successfully installed at 'C:\Users\maxr\AppData\Local\Fork\git\bin\git.exe'.
```

**Comment by DanPristupov** [comment]
Hi. That's strange, I've never heard about such a problem yet.

The warning `Open WARNING: Can not open the file as [7z] archive` is very suspicious. Could you re-download the installer again please?

Do you have a x64 Windows?

Update 1: Just a clarification. Fork installer contains a standalone archive of standalone git package and extracts it using 7z. In your case 7z told, that the target file is not a 7z archive which is very strange.

Do you have an antivirus which could block the archive extracting?

**Comment by siburny** [comment]
Yes, I am on Windows 10 x64. Uninstalled, deleted all folders, reinstalled, and the same error appeared.

Insteresting thing is that 7z file is extracted here `c:\ProgramData\maxr\Fork\` in `git` subfolder; I can see all files. My assumption is that copying that folder to `c:\Users\maxr\AppData\Local\Fork` fails (this is where app expects it).

```
Can not open the file as [7z] archive
The file is open as [PE] archive
```

In reality, that warning is correct: 7z filename should be `PortableGit-2.18.0-64-bit.7z.exe` because it's self-extracting archive. But [IMHO] because of that warning copying of files is aborted.

Another intersting tidbit: two log lines with same timestamp BUT opposite meaning.
```
E 2018-11-16 17:06:12.412 Git instance installation failed and can not be found at 'C:\Users\maxr\AppData\Local\Fork\git\bin\git.exe'.
I 2018-11-16 17:06:12.412 Git instance successfully installed at 'C:\Users\maxr\AppData\Local\Fork\git\bin\git.exe'.
```

**Comment by siburny** [comment]
Just tried installing the newer version, and got the same problem:
```
D 2018-11-20 10:48:41.474 Loading settings.
I 2018-11-20 10:48:41.509 Start ipc server Fork_22940_Pipe_AskPass
D 2018-11-20 10:48:41.509 Waiting for next cross-process event '802'
I 2018-11-20 10:48:58.734 7Zip found at 'C:\ProgramData\maxr\Fork\app-1.23.5\7z.exe'
I 2018-11-20 10:48:58.734 Git installation package found at 'C:\ProgramData\maxr\Fork\app-1.23.5\PortableGit-2.19.1-64-bit.7z'.
I 2018-11-20 10:48:58.734 Running 'C:\ProgramData\maxr\Fork\app-1.23.5\7z.exe' with arguments '-o../gitInstance/2.19.1 -bsp2 x "C:\ProgramData\maxr\Fork\app-1.23.5\PortableGit-2.19.1-64-bit.7z" -y'.
D 2018-11-20 10:49:09.499 Output: 
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Scanning the drive for archives:
1 file, 40263400 bytes (39 MiB)

Extracting archive: C:\ProgramData\maxr\Fork\app-1.23.5\PortableGit-2.19.1-64-bit.7z
WARNING:
C:\ProgramData\maxr\Fork\app-1.23.5\PortableGit-2.19.1-64-bit.7z
Can not open the file as [7z] archive
The file is open as [PE] archive

--
Path = C:\ProgramData\maxr\Fork\app-1.23.5\PortableGit-2.19.1-64-bit.7z
Open WARNING: Can not open the file as [7z] archive
Type = PE
Physical Size = 40263400
CPU = x86
Characteristics = Executable 32-bit
Created = 2017-04-05 17:33:08
Headers Size = 1024
Checksum = 40305508
Name = 7zS.sfx.exe
Image Size = 503808
Section Alignment = 4096
File Alignment = 512
Code Size = 382976
Initialized Data Size = 106496
Uninitialized Data Size = 0
Linker Version = 14.10
OS Version = 6.0
Image Version = 0.0
Subsystem Version = 6.0
Subsystem = Windows GUI
DLL Characteristics = Relocated NX-Compatible TerminalServerAware
Stack Reserve = 1048576
Stack Commit = 4096
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment = FileVersion: 16.4.0.0
FileVersion: 16.04
ProductVersion: 16.4.0.0
ProductVersion: 16.04
CompanyName: Igor Pavlov
FileDescription: 7z Setup SFX
InternalName: 7zS.sfx
LegalCopyright: Copyright (c) 1999-2016 Igor Pavlov
OriginalFilename: 7zS.sfx.exe
ProductName: 7-Zip
----
Path = [0]
Size = 39778896
Packed Size = 39778896
Virtual Size = 39778896
Offset = 477184
--
Path = [0]
Type = 7z
Offset = 515
Physical Size = 39778376
Tail Size = 5
Headers Size = 60770
Method = LZMA:28 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Archives with Warnings: 1
Folders: 11
Files: 5780
Size:       264130375
Compressed: 40263400

D 2018-11-20 10:49:09.499 Error:   0M Scan C:\ProgramData\maxr\Fork\app-1.23.5\
                                              
  0% Open
         
  0%
    
  3% 127 - mingw64\lib\tcl8.6\encoding\cp949.enc
                                                
  3% 287 - mingw64\lib\tcl8.6\msgs\sh.msg
                                         
  3% 434 - mingw64\lib\tcl8.6\tzdata\America\Guatemala
                                                      
  3% 575 - mingw64\lib\tcl8.6\tzdata\Asia\Dushanbe
                                                  
  3% 723 - mingw64\lib\tcl8.6\tzdata\Etc\GMT-14
                                               
  3% 858 - mingw64\lib\tcl8.6\tzdata\Pacific\Kwajalein
                                                      
  3% 1016 - mingw64\lib\tk8.6\demos\ttkscale.tcl
                                                
  3% 1155 - mingw64\libexec\git-core\mergetools\meld
                                                    
  4% 1291 - mingw64\share\doc\git-doc\git-pack-refs.html
                                                        
  6% 1416 - mingw64\share\doc\git-doc\technical\api-submodule-config.html
                                                                         
  7% 1525 - mingw64\share\git-gui\lib\sshkey.tcl
                                                
 10% 1646 - usr\bin\core_perl\xsubpp
                                    
 10% 1796 - usr\lib\perl5\core_perl\Sys\Syslog.pm
                                                 
 10% 1941 - usr\lib\terminfo\73\screen.linux-m1
                                               
 10% 2107 - usr\share\icons\locolor\16x16\apps\gvim.png
                                                       
 14% 2222 - usr\share\perl5\core_perl\Carp.pm
                                             
 14% 2338 - usr\share\perl5\core_perl\Net\FTP\dataconn.pm
                                                         
 14% 2483 - usr\share\perl5\core_perl\unicore\Blocks.txt
                                                        
 16% 2577 - usr\share\perl5\core_perl\unicore\lib\Ccc\A.pl
                                                          
 16% 2699 - usr\share\perl5\core_perl\unicore\lib\InSC\Number.pl
                                                                
 16% 2805 - usr\share\perl5\core_perl\unicore\lib\Nv\70.pl
                                                          
 16% 2916 - usr\share\perl5\core_perl\unicore\lib\Scx\Knda.pl
                                                             
 16% 3032 - usr\share\perl5\vendor_perl\HTTP\Response.pm
                                                        
 16% 3174 - usr\share\pki\ca-trust-source\ca-bundle.trust.crt
                                                             
 17% 3299 - usr\share\terminfo\78\xterm-x11hilite
                                                 
 17% 3450 - usr\share\vim\vim81\doc\arabic.txt
                                              
 19% 3558 - usr\share\vim\vim81\doc\usr_23.txt
                                              
 21% 3683 - usr\share\vim\vim81\ftplugin\kconfig.vim
                                                    
 21% 3830 - usr\share\vim\vim81\indent\cucumber.vim
                                                   
 21% 3972 - usr\share\vim\vim81\keymap\persian.vim
                                                  
 22% 4093 - usr\share\vim\vim81\lang\menu_ko.utf-8.vim
                                                      
 23% 4183 - usr\share\vim\vim81\macros\hanoi\poster
                                                   
 25% 4294 - usr\share\vim\vim81\syntax\ampl.vim
                                               
 25% 4443 - usr\share\vim\vim81\syntax\fasm.vim
                                               
 25% 4600 - usr\share\vim\vim81\syntax\msidl.vim
                                                
 27% 4720 - usr\share\vim\vim81\syntax\sendpr.vim
                                                 
 27% 4870 - usr\share\vim\vim81\syntax\xslt.vim
                                               
 27% 4901 - usr\share\vim\vim81\tutor\tutor.bar.utf-8
                                                     
 30% 5004 - mingw64\bin\git-lfs.exe
                                   
 35% 5018 - mingw64\bin\libgcc_s_seh-1.dll
                                          
 40% 5061 - mingw64\bin\tclsh.exe
                                 
 44% 5141 - mingw64\libexec\git-core\git-fetch-pack.exe
                                                       
 51% 5225 - mingw64\libexec\git-core\git-unpack-objects.exe
                                                           
 60% 5294 - usr\bin\bzip2recover.exe
                                    
 63% 5344 - usr\bin\gdbus.exe
                             
 67% 5418 - usr\bin\msys-apr-1-0.dll
                                    
 73% 5453 - usr\bin\msys-gssapi-3.dll
                                     
 76% 5509 - usr\bin\msys-sqlite3rbu-0.dll
                                         
 81% 5582 - usr\bin\psl.exe
                           
 87% 5662 - usr\bin\vdir.exe
                            
 95% 5722 - usr\lib\perl5\core_perl\auto\Fcntl\Fcntl.dll
                                                        

E 2018-11-20 10:49:09.499 Git instance installation finished, but can not be found at 'C:\Users\maxr\AppData\Local\Fork\gitInstance\2.19.1\bin\git.exe'.
I 2018-11-20 10:49:16.535 Fork 1.23.5.0 at C:\ProgramData\maxr\Fork\app-1.23.5\Fork.exe --squirrel-firstrun
I 2018-11-20 10:49:16.535 Git Location: C:\Users\maxr\AppData\Local\Fork\gitInstance\2.19.1\bin\git.exe
I 2018-11-20 10:49:16.535 Log target: AppData log file
I 2018-11-20 10:49:16.574 Last update check: 11/20/2018 10:31:10 AM. Next one: 11/21/2018 10:31:10 AM
I 2018-11-20 10:49:16.857 Restoring 1 sessions.
I 2018-11-20 10:49:16.897 Main: 240, Window: 35414, WindowLoaded: 321, UiReady: 41, Total: 35776
```

**Comment by siburny** [comment]
I am closing this issue since latest version doesn't exhibit this problem

**Comment by DanPristupov** [comment]
Thank you for getting back.
We didn't change much in the installation process since then.
Most probably it was some problem with Windows or/and antivirus on your computer.

**Comment by arisjramos** [comment]
Version 1.38 seems to have the same problem
`
I 2019-10-11 14:26:29.476 7Zip found at 'C:\ProgramData\arj\Fork\app-1.40.2\7z.exe'
I 2019-10-11 14:26:29.476 Git installation package found at 'C:\ProgramData\arj\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z'.
I 2019-10-11 14:26:29.493 Running 'C:\ProgramData\arj\Fork\app-1.40.2\7z.exe' with arguments '-o../gitInstance/2.20.1 -bsp2 x "C:\ProgramData\arj\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z" -y'.
D 2019-10-11 14:26:37.062 Output: 
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Extracting archive: C:\ProgramData\arj\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z
WARNING:
C:\ProgramData\arj\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z
Can not open the file as [7z] archive
The file is open as [PE] archive
...
E 2019-10-11 14:26:37.069 Git instance installation finished, but can not be found at 'C:\Users\arj\AppData\Local\Fork\gitInstance\2.20.1\bin\git.exe'.
...

**Comment by siburny** [comment]
I still stumble upon this issue time to time. I just manually extract the 7z file and put it in a proper folder.

**Comment by b47on** [comment]
Same here:

I 2019-10-14 22:02:26.836 7Zip found at 'C:\ProgramData\stkoc\Fork\app-1.40.2\7z.exe'
I 2019-10-14 22:02:26.845 Git installation package found at 'C:\ProgramData\stkoc\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z'.
I 2019-10-14 22:02:26.845 Running 'C:\ProgramData\stkoc\Fork\app-1.40.2\7z.exe' with arguments '-o../gitInstance/2.20.1 -bsp2 x "C:\ProgramData\stkoc\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z" -y'.
D 2019-10-14 22:02:38.671 Output: 
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Scanning the drive for archives:
1 file, 42276424 bytes (41 MiB)

Extracting archive: C:\ProgramData\stkoc\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z
WARNING:
C:\ProgramData\stkoc\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z
Can not open the file as [7z] archive
The file is open as [PE] archive

--
Path = C:\ProgramData\stkoc\Fork\app-1.40.2\PortableGit-2.20.1-64-bit.7z
Open WARNING: Can not open the file as [7z] archive
Type = PE
Physical Size = 42276424
CPU = x86
Characteristics = Executable 32-bit
Created = 2017-04-06 00:33:08
Headers Size = 1024
Checksum = 42338504
Name = 7zS.sfx.exe

**Comment by DanPristupov** [comment]
> C:\**ProgramData**\stkoc\Fork\

Is that possible that you run the installer with admin rights? Fork should be installed to the application data by default.

**Comment by omar-caraveo** [comment]
I encountered same problem on my brand new laptop (Win10; Fork 1.42.6.0; Git 2.24.1).
This is my workaround:

1. Download "Git for Windows Portable" (from https://git-scm.com/download/win)
2. Extract 'PortableGit' into C:\Users\<user>\AppData\Local\Fork\gitInstance\<fork.version>
3. Run Fork as Administrator

**Comment by jmfranck** [comment]
Same issue here.

```
?? 2022-08-17 11:24:42.567 Use default settings
?? 2022-08-17 11:24:42.588 
          _               _                _               _
         /\ \            /\ \             /\ \            /\_\
        /  \ \          /  \ \           /  \ \          / / /  _
       / /\ \ \        / /\ \ \         / /\ \ \        / / /  /\_\   Fork 1.76.5.0
      / / /\ \_\      / / /\ \ \       / / /\ \_\      / / /__/ / /   Git: C:\Users\jmfranck\AppData\Local\Fork\gitInstance\2.36.1\bin\git.exe
     / /_/_ \/_/     / / /  \ \_\     / / /_/ / /     / /\_____/ /    Update Channel: Develop
    / /____/\       / / /   / / /    / / /__\/ /     / /\_______/
   / /\____\/      / / /   / / /    / / /_____/     / / /\ \ \          https://fork.dev
  / / /           / / /___/ / /    / / /\ \ \      / / /  \ \ \
 / / /           / / /____\/ /    / / /  \ \ \    / / /    \ \ \
 \/_/            \/_________/     \/_/    \_\/    \/_/      \_\_\

?? 2022-08-17 11:24:42.598 Start IPC server Fork_Pipe8732_AskPass
?? 2022-08-17 11:24:42.598 Start IPC server Fork_Pipe8732_Default
?? 2022-08-17 11:24:42.598 Fork_Pipe8732_Default: waiting for next event '571'
?? 2022-08-17 11:24:42.598 Fork_Pipe8732_AskPass: waiting for next event '571'
?? 2022-08-17 11:25:20.457 7Zip found at 'C:\ProgramData\jmfranck\Fork\app-1.76.5\7z.exe'
?? 2022-08-17 11:25:20.457 Git installation package found at 'C:\ProgramData\jmfranck\Fork\app-1.76.5\PortableGit-2.36.1-64-bit.7z'.
?? 2022-08-17 11:25:20.457 Running 'C:\ProgramData\jmfranck\Fork\app-1.76.5\7z.exe' with arguments '-o../gitInstance/2.36.1 -bsp2 x "C:\ProgramData\jmfranck\Fork\app-1.76.5\PortableGit-2.36.1-64-bit.7z" -y'.
?? 2022-08-17 11:25:26.890 Output: 
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 45568272 bytes (44 MiB)

Extracting archive: C:\ProgramData\jmfranck\Fork\app-1.76.5\PortableGit-2.36.1-64-bit.7z
WARNING:
C:\ProgramData\jmfranck\Fork\app-1.76.5\PortableGit-2.36.1-64-bit.7z
Can not open the file as [7z] archive
The file is open as [PE] archive

--
Path = C:\ProgramData\jmfranck\Fork\app-1.76.5\PortableGit-2.36.1-64-bit.7z
Open WARNING: Can not open the file as [7z] archive
Type = PE
Physical Size = 45568272
CPU = x86
Characteristics = Executable 32-bit
Created = 2019-08-02 09:43:26
Headers Size = 1024
Checksum = 45594803
Name = 7zS.sfx.exe
Image Size = 524288
Section Alignment = 4096
File Alignment = 512
Code Size = 404992
Initialized Data Size = 109056
Uninitialized Data Size = 0
Linker Version = 14.22
OS Version = 6.0
Image Version = 0.0
Subsystem Version = 6.0
Subsystem = Windows GUI
DLL Characteristics = Relocated NX-Compatible TerminalServerAware
Stack Reserve = 1048576
Stack Commit = 4096
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment = 
{
FileVersion: 19.0.0.0
FileVersion: 19.00
ProductVersion: 19.0.0.0
ProductVersion: 19.00
CompanyName: Igor Pavlov
FileDescription: 7z Setup SFX
InternalName: 7zS.sfx
LegalCopyright: Copyright (c) 1999-2018 Igor Pavlov
OriginalFilename: 7zS.sfx.exe
ProductName: 7-Zip
}
----
Path = [0]
Size = 45055392
Packed Size = 45055392
Virtual Size = 45055392
Offset = 501248
--
Path = [0]
Type = 7z
Offset = 512
Physical Size = 45054875
Tail Size = 5
Headers Size = 63872
Method = LZMA:28 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Archives with Warnings: 1
Folders: 13
Files: 6106
Size:       297192765
Compressed: 45568272

?? 2022-08-17 11:25:26.890 Error:   0M Scan C:\ProgramData\jmfranck\Fork\app-1.76.5\
                                                  
  0% Open
         
  0%
    
  1% 414 - mingw64\lib\tcl8.6\tzdata\America\Costa_Rica
                                                       
  2% 836 - mingw64\lib\tcl8.6\tzdata\Mexico\BajaNorte
                                                     
  3% 1237 - mingw64\share\doc\git-doc\git-diff.html
                                                   
  8% 1605 - mingw64\ssl\ct_log_list.cnf.dist
                                            
  9% 1927 - usr\lib\terminfo\73\screen-16color-s
                                                
 12% 2259 - usr\share\nano\lua.nanorc
                                     
 14% 2587 - usr\share\perl5\core_perl\unicore\SpecialCasing.txt
                                                               
 15% 3018 - usr\share\perl5\core_perl\unicore\lib\Sc\Han.pl
                                                           
 16% 3409 - usr\share\terminfo\73\screen.xterm-new
                                                  
 18% 3771 - usr\share\vim\vim82\doc\tagsrch.txt
                                               
 21% 4172 - usr\share\vim\vim82\indent\raku.vim
                                               
 23% 4538 - usr\share\vim\vim82\plugin\tohtml.vim
                                                 
 25% 4882 - usr\share\vim\vim82\syntax\logindefs.vim
                                                    
 27% 5293 - usr\share\vim\vim82\tutor\tutor.nb.utf-8
                                                    
 29% 5390 - mingw64\bin\git-credential-helper-selector.exe
                                                          
 35% 5402 - mingw64\bin\libcurl-4.dll
                                     
 42% 5437 - mingw64\bin\tcl86.dll
                                 
 49% 5566 - mingw64\libexec\git-core\git-mktag.exe
                                                  
 61% 5675 - usr\bin\b2sum.exe
                             
 66% 5738 - usr\bin\getconf.exe
                               
 71% 5823 - usr\bin\msys-gcc_s-seh-1.dll
                                        
 77% 5851 - usr\bin\msys-psl-5.dll
                                  
 85% 5948 - usr\bin\ssh-keyscan.exe
                                   
 92% 6025 - usr\lib\gettext\hostname.exe
                                        
 98% 6099 - usr\lib\perl5\vendor_perl\auto\Term\ReadKey\ReadKey.dll
                                                                   

? 2022-08-17 11:25:26.890 Git instance installation finished, but can not be found at 'C:\Users\jmfranck\AppData\Local\Fork\gitInstance\2.36.1\bin\git.exe'.
?? 2022-08-17 11:25:26.890 Running 'C:\Users\jmfranck\AppData\Local\Fork\gitInstance\2.36.1\bin\git.exe' with arguments 'config --system credential.helper manager-core'.
? 2022-08-17 11:25:26.906 Cannot enable git credential manager for 'C:\Users\jmfranck\AppData\Local\Fork\gitInstance\2.36.1\bin\git.exe'
? 2022-08-17 11:25:26.906 System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fork.Shell.Interaction.ShellRequest.Execute()
   at Fork.Git.Commands.EnableGitCredentialManagerGitCommand.Execute(Boolean force)
```

**Comment by jmfranck** [comment]
updating that for me, this issue was caused by applocker *even though I ran the installer from an applocker-allowed directory* (typically enough to allow a program install).

To get it to work, I had to uninstall, delete the `AppData\Local\Fork` directory, add an AppLocker rule based on publisher, and re-run.
