### ISSUE TITLE
[BUG] "Open repository..." crashes Fork entirely

### ISSUE THREAD

**Issue by RareSecond** [ForkIssues/TrackerWin#524]
Tried it a couple of times, always end up with a crashing Fork. It used to work before, but with the latest update, it no longer does..

Fork version 1.41.0.0
Computer: Windows 10 Pro v1903

If there's any additional info I can provide, don't hesitate to ask!

**Comment by DanPristupov** [comment]
Where is "Open repository..."? Is this a menu item?

**Comment by RareSecond** [comment]
Hi @DanPristupov, it indeed is the menu item that's under "File" (or the Control+O) shortcut.

**Comment by DanPristupov** [comment]
Do have disabled Windows themes (or High Contrast mode) may be? (https://github.com/ForkIssues/TrackerWin/issues/282#issuecomment-521273271)

**Comment by RareSecond** [comment]
I just checked, and am using neither of those..

I was however able to drag my folder into Fork from my file explorer, so for now I'm "helped".

But to reiterate: it all used to work until a couple of days ago, and didn't change anything too meaningful about my system..

**Comment by attilaantal** [comment]
Recently Fork started crashing on my PC as well. I can open the application, then I want to open one of the Repositories from the Quick Launch and it closes. No obvious error is shown, so I waited minutes until I realized it isn't running anymore.
I've tried opening different Repositories, the issue the same. 

While researching the problem I found that it might be a corrupted User Profile. So I created a brand new profile on the PC. The Fork application worked well, so I am thinking it is somewhat related to the user profile. Can't understand what could go wrong by working on the same apps every single day for months/years now.

I've tried using the default Windows Theme, and it did not help.

There was a Windows OS update a couple of days ago which didn't seem to be the cause as I was able to open Fork after that.

Every time the Fork crashes, there are two Error logs in the Windows Event Viewer:

**Application Error**

```
Faulting application name: Fork.exe, version: 1.59.0.0, time stamp: 0x6026aa48
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0xb610d74d
Exception code: 0xe0434352
Fault offset: 0x0012a8b2
Faulting process id: 0xf98
Faulting application start time: 0x01d71070cfa29da7
Faulting application path: C:\Users\Attila\AppData\Local\Fork\app-1.59.0\Fork.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6bbbd387-bfbe-4658-ac73-2c0a023bf674
Faulting package full name: 
Faulting package-relative application ID: 
```

**.NET Runtime**

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArithmeticException

Exception Info: System.OverflowException
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(System.Windows.Media.Imaging.BitmapSource, System.Windows.Media.ColorContext, System.Windows.Media.ColorContext, System.Windows.Media.PixelFormat)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(System.Uri, System.Net.Cache.RequestCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(System.Uri)
   at Fork.UI.UserControls.FileListUserControl..cctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Fork.UI.UserControls.RepositoryUserControl.InitializeComponent()
   at Fork.UI.UserControls.RepositoryUserControl..ctor()
   at Fork.UI.TabItemView.ActivateRepositoryViewMode(Fork.Git.GitModule)
   at Fork.TabManager.CreateNewTab(Fork.UI.TabItemMode, Fork.Git.GitModule, Fork.Git.GitModule)
   at Fork.TabManager.OpenRepository(System.String, Fork.Git.GitModule)
   at Fork.UI.Commands.RepositoryManager.OpenRepositoryCommand.Execute(Repository)
   at Fork.UI.QuickLaunch.QuickLaunchWindow.SubmitSelectedItem()
   at Fork.UI.QuickLaunch.QuickLaunchWindow.RepositoriesListBox_MouseUp(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Fork.App.Main()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.Main(System.String[])
```

**Comment by DanPristupov** [comment]
@attilaantal https://github.com/fork-dev/TrackerWin/issues/847#issuecomment-682370957

**Comment by attilaantal** [comment]
> @attilaantal [#847 (comment)](https://github.com/fork-dev/TrackerWin/issues/847#issuecomment-682370957)

Thank you, Dan! I am sorry, I have missed that post earlier even after researching for a couple of hours.

**Comment by Prohibition-rare** [comment]
@RareSecond https://stackdev.space/questions/further-challenges-await-in-my-text-based-adventure-game
