### ISSUE TITLE
Fork doesn't work .bashrc

### ISSUE THREAD

**Issue by saurabhray91** [ForkIssues/TrackerWin#770]
I have configured ~/.bashrc with certain environment variables for my project and is required for git operations as well but Fork doesn't seem to work well with it. I get the following error -

```
husky > pre-push (node v10.19.0)
husky > pre-push hook failed (add --no-verify to bypass)

Pushing to https://github.com/<my-repo>
Error: Failed to replace env in config: ${TOKEN}
    at HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\config\core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\config\core.js:411:12)
    at parseField (HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\config\core.js:389:7)
    at HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\config\core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\config\core.js:328:23)
    at ConfigChain.addString (HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\config\core.js:316:10)
    at HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16
HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\npm.js:59:13)
    at process.errorHandler (HOME\AppData\Roaming\nvm\v10.19.0\node_modules\npm\lib\utils\error-handler.js:205:32)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:497:27)
error: failed to push some refs to 'https://github.com/<my-repo>.git'

```

Please note that git operations work perfectly on my terminal

**Comment by DanPristupov** [comment]
> Please note that git operations work perfectly on my terminal

Try to start Fork from terminal
