### ISSUE TITLE
Error on rebase operation after merge all conflicts

### ISSUE THREAD

**Issue by AlexanderPhilippov** [ForkIssues/TrackerWin#890]
Operation system: windows 10
Fork version: 1.52.1.0
Error:

> Done 11 entries.
Todo 1 entries.
Current entry: Pick  5d2ea3478ad83c2a6a99a3f4dbdf55ccc8e8ddf7
Next entry: Pick  5f3a0f8589b019feb2d4b5236abbf5c133f5522e
Ask message for  5d2ea3478ad83c2a6a99a3f4dbdf55ccc8e8ddf7
Cant encode: D:\Source\my-project\.git\rebase-merge\fork-message-archive: System.IO.FileNotFoundException: Could not find file 'D:\Source\my-project\.git\rebase-merge\fork-message-archive'.
File name: 'D:\Source\my-project\.git\rebase-merge\fork-message-archive'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Fork.RI.Program.WriteMessage(String sha, String outputTodoPath)

> Aborting commit due to empty commit message.

> error: could not commit staged changes.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/629
