### ISSUE TITLE
Fork 1.54.0 and 1.54.1 Crashing

### ISSUE THREAD

**Issue by dsbert** [ForkIssues/TrackerWin#958]
Fork 1.54.0 and 1.54.1 are crashing at start up. When launching, I can see the process start and immediately close without the main window appearing.

Here is the error from Windows Event Viewer

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at Fork.Shell.Interaction.ShellRequest.Execute()
   at Fork.Git.Commands.EnableGitCredentialManagerGitCommand.Execute(Boolean)
   at Fork.App.InitializeForkInstance()
   at Fork.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Fork.App.Main()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.Main(System.String[])
```

**Comment by DanPristupov** [comment]
Do you have a git instance in `%localappdata%\fork\gitInstance\2.26.2\`?

Can you send the log file from `%localappdata%\fork\logs\fork.log` to support@fork.dev please?

**Comment by dsbert** [comment]
I replied via email, thanks

**Comment by DanPristupov** [comment]
The problem was caused by modifications in the Fork installation directory (the internal git instance was removed).

**Comment by dsbert** [comment]
According to this issue https://github.com/ForkIssues/TrackerWin/issues/282#issuecomment-531288594

I should be able to set the git instance using an environment variable. Are you saying this no longer works?

**Comment by DanPristupov** [comment]
> Are you saying this no longer works?

No! It must work, I didn't touch it.

**Comment by dsbert** [comment]
> 
> 
> > Are you saying this no longer works?
> 
> No! It must work, I didn't touch it.

In that case, removing the internal git instance should not be a problem, correct?

**Comment by dsbert** [comment]
I created a symbolic link to git in `%localappdata%/fork/gitinstance/2.62.2/` and fork launches now. So it seems that you are correct in why Fork is crashing. However, it also seems that the git envrionment variable `FORKGITINSTANCE` has stopped working.

**Comment by DanPristupov** [comment]
Manual modification of the Fork installation directory was never discussed or documented. You can do it on your own risk expecting that one day it will stop working.

I expect the internal git instance to be in the Fork directory, because I put it here myself on the installation. Fork 1.54 makes some minor maintenance of the internal git instance and crashes when the files miss.

**Comment by DanPristupov** [comment]
> I created a symbolic link to git in %localappdata%/fork/gitinstance/2.62.2/ and fork launches now.

What is the point of this? What are you trying to achieve?

> However, it also seems that the git envrionment variable FORKGITINSTANCE has stopped working.

What should I do to reproduce the problem?

**Comment by dsbert** [comment]
> What is the point of this? What are you trying to achieve?

It was just an attempt to confirm what you said, and to see if I can get the application running.

> > However, it also seems that the git envrionment variable FORKGITINSTANCE has stopped working.
> 
> What should I do to reproduce the problem?

I understand your point about modifying the installation directory not being supported. Can you please clarify the purpose or expectation of `%FORKGETINSTANCE%`?

Here are the steps to reproduce the crash.

1. Install fork (using the official installer)
2. Rename `%localappdata%/fork/gitinstance` to `%localappdata%/fork/somethingelse`
3. Set the environment variable `FORKGITINSTANCE=%localappdata%/fork/somethingelse`
4. Try to start Fork - it crashes.
5. Copy `%localappdata%/fork/somethingelse` back to `%localappdata%/fork/gitinstance`
6. Try to start Fork - it works. Opening the preferences page in Fork indicates that it is using the git instance provided by the environment variable.

So when I say that the environment variable is not working, I mean that Fork is not using the `%FORKGITINSTANCE%` variable at start up to perform whatever maintenance tasks you mentioned, but instead using the internal git installation. Is this the expected and desired outcome?

**Comment by DanPristupov** [comment]
> ... Fork is not using the %FORKGITINSTANCE% variable at start up to perform whatever maintenance tasks you mentioned, but instead using the internal git installation. Is this the expected and desired outcome?

This is the correct behavior. Fork does differentiate internal and a custom git instances
- When you switch Fork to a custom git instance (either using Preferences dialog, `settings.json` file or `%FORKGITINSTANCE%` environment variable), it will use this git instance for all operations in your repositories
- However Fork will also keep the internal git instance up-to-date for a case if you decide to switch back to it.

**Comment by dsbert** [comment]
Thank you for clarifying and for the quick responses.

I'll close this issue now.

**Comment by DanPristupov** [comment]
I will make it work again in the next update, however I think this problem has occurred because nobody asked me whether it's OK to modify the directory (or at least inform me about it).

For comparison, there are applications which read the Fork settings file directly and use it in some way. When the developers contacted me and described the use case I explained how to easier achieve what they want. Now, when I add new settings, I keep in mind that I should be very careful and not break things for those guys.

**Comment by dsbert** [comment]
That makes perfect sense and I appreciate you going above and beyond to work with other developers. I agree with your points about modifying the internals of software without understanding / communicating intent.

I did not create the scoop manifest for Fork but did track down the original issue here https://github.com/lukesampson/scoop-extras/issues/1094 which may have more context.

**Comment by dsbert** [comment]
I did not see anything in the release notes related to this issue, but it seems that Fork 1.55 is working with scoop again.
